import React,{useEffect,useRef,useState}from'react';
import{createClient}from'genlayer-js';import{studionet}from'genlayer-js/chains';import{TransactionStatus}from'genlayer-js/types';
import{Vote,GitCompare,ShieldCheck,RefreshCw,ExternalLink,Users}from'lucide-react';
const CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||'';const configured=/^0x[a-fA-F0-9]{40}$/.test(CONTRACT)&&!/^0x0{40}$/.test(CONTRACT);const EXPLORER='https://explorer-studio.genlayer.com';const EVIDENCE='https://github.com/Azaria723/RepoLicenseCouncil/blob/master/verification/studionet-verification.md';const reader=()=>createClient({chain:studionet});const short=(v='')=>v.length>16?`${v.slice(0,8)}…${v.slice(-6)}`:v;
const defaultPolicy=JSON.stringify({allowed:['permissive'],requires_vote:['copyleft'],prohibited_characteristics:['network-copyleft']});
export default function App(){const[account,setAccount]=useState(''),[counts,setCounts]=useState({council_count:0,case_count:0}),[councils,setCouncils]=useState([]),[cases,setCases]=useState([]),[notice,setNotice]=useState(''),[hash,setHash]=useState(''),[busy,setBusy]=useState(false),[choice,setChoice]=useState('ACCEPT');const lock=useRef(false);
 const[council,setCouncil]=useState({owner:'Azaria723',repo:'RepoLicenseCouncil',path:'/evidence/demo-project/LICENSE',members:'',quorum:'2',policy:defaultPolicy});const[proposal,setProposal]=useState({councilId:'0',oldCommit:'',oldDigest:'',newCommit:'',newDigest:'',hours:'24'});const[selected,setSelected]=useState('0');
 const read=async(name,args=[])=>JSON.parse(await reader().readContract({address:CONTRACT,functionName:name,args}));async function refresh(){if(!configured)return;const c=await read('get_counts');setCounts(c);setCouncils(await Promise.all(Array.from({length:c.council_count},(_,i)=>read('get_council',[BigInt(i)]))));setCases(await Promise.all(Array.from({length:c.case_count},(_,i)=>read('get_case',[BigInt(i)]))));}
 useEffect(()=>{refresh().catch(e=>setNotice(e.message));const eth=window.ethereum,changed=a=>setAccount(a[0]||'');eth?.request({method:'eth_accounts'}).then(changed).catch(()=>{});eth?.on?.('accountsChanged',changed);return()=>eth?.removeListener?.('accountsChanged',changed)},[]);
 async function connect(){try{if(!window.ethereum)throw Error('Install a compatible wallet.');setAccount((await window.ethereum.request({method:'eth_requestAccounts'}))[0]||'')}catch(e){setNotice(e.message)}}
 async function write(name,args){if(lock.current)return;lock.current=true;setBusy(true);setHash('');try{if(!configured)throw Error('Deploy the contract and configure VITE_CONTRACT_ADDRESS.');if(!account)throw Error('Connect wallet first.');if(BigInt(await window.ethereum.request({method:'eth_chainId'}))!==61999n)throw Error('Switch wallet to Studionet chain 61999.');const client=createClient({chain:studionet,provider:window.ethereum,account});setNotice(`Confirm ${name} in your wallet.`);const tx=await client.writeContract({address:CONTRACT,functionName:name,args});setHash(tx);setNotice('Submitted. Waiting for finality…');await reader().waitForTransactionReceipt({hash:tx,status:TransactionStatus.FINALIZED});await refresh();setNotice(`${name} finalized. Authoritative state refreshed.`)}catch(e){setNotice(e.message)}finally{setBusy(false);lock.current=false}}
 function create(e){e.preventDefault();let members;try{members=council.members.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);if(members.length<2)throw 0;JSON.parse(council.policy)}catch{return setNotice('Provide at least two member addresses and valid policy JSON.')}write('create_council',[council.owner,council.repo,council.path,JSON.stringify(members),BigInt(council.quorum),council.policy])}
 function propose(e){e.preventDefault();const deadline=BigInt(Math.floor(Date.now()/1000)+Number(proposal.hours)*3600);write('propose_change',[BigInt(proposal.councilId),proposal.oldCommit,proposal.oldDigest,proposal.newCommit,proposal.newDigest,deadline])}
 const active=cases.find(x=>String(x.case_id)===selected);const activeCouncil=active&&councils[active.council_id];const licenseAt=commit=>activeCouncil?`https://github.com/${encodeURIComponent(activeCouncil.repo_owner)}/${encodeURIComponent(activeCouncil.repo_name)}/blob/${commit}/${activeCouncil.license_path.replace(/^\//,'').split('/').map(encodeURIComponent).join('/')}`:null;let diagnostics;try{diagnostics=active?.diagnostics&&JSON.parse(active.diagnostics)}catch{diagnostics=null}
 return <div><header><a className="brand" href="#top"><img src="/logo.png" alt="RepoLicenseCouncil logo"/><div><b>RepoLicenseCouncil</b><span>Evidence-grounded governance</span></div></a><nav><a href="#council">Council</a><a href="#cases">Cases</a><a href={EVIDENCE} target="_blank" rel="noopener noreferrer">Live evidence ↗</a></nav><button className="connect" onClick={connect}>{account?short(account):'Connect wallet'}</button></header><main id="top"><section className="hero"><div><p className="eyebrow">GITHUB PROVENANCE · HUMAN QUORUM</p><h1>License facts by validators.<br/><em>Decisions by your council.</em></h1><p>Verify an exact repository license change across immutable commits, freeze the bounded semantic result, then let members decide whether the project accepts it.</p><div className="buttons"><a href="#council">Open a council</a><button onClick={()=>refresh().catch(e=>setNotice(e.message))}><RefreshCw/> Refresh state</button><a className="secondary-link" href={EVIDENCE} target="_blank" rel="noopener noreferrer">Review live proof <ExternalLink/></a></div></div><aside><img src="/logo.png" alt="License document and council shield"/><Stat label="Network" value="Studionet · 61999"/><Stat label="Councils" value={counts.council_count}/><Stat label="Cases" value={counts.case_count}/><div className="stat"><span>Contract</span>{configured?<a href={`${EXPLORER}/address/${CONTRACT}`} target="_blank" rel="noopener noreferrer">{short(CONTRACT)} ↗</a>:<b>Awaiting deploy</b>}</div></aside></section>
 <section className="principles"><article><ShieldCheck/><div><b>Canonical evidence</b><p>Commit tree, blob identity and fetched-byte digest are independently verified.</p></div></article><article><GitCompare/><div><b>Bounded semantics</b><p>Validators classify license change facts without deciding governance.</p></div></article><article><Users/><div><b>Member authority</b><p>Only council votes and quorum create the final decision.</p></div></article></section>
 <div className="notice">{notice||'Connect a wallet to interact with authoritative contract state.'}{hash&&<a href={`${EXPLORER}/tx/${hash}`} target="_blank" rel="noopener noreferrer">View transaction <ExternalLink/></a>}</div>
 <section id="council" className="workspace"><form onSubmit={create}><Head n="01" kicker="GOVERNANCE" title="Create council"/><Grid><Field label="GitHub owner" value={council.owner} set={v=>setCouncil({...council,owner:v})}/><Field label="Repository" value={council.repo} set={v=>setCouncil({...council,repo:v})}/></Grid><Field label="Canonical LICENSE path" value={council.path} set={v=>setCouncil({...council,path:v})}/><label>Member addresses<textarea placeholder="One per line or comma-separated" value={council.members} onChange={e=>setCouncil({...council,members:e.target.value})}/></label><Field label="Quorum" type="number" value={council.quorum} set={v=>setCouncil({...council,quorum:v})}/><label>Policy JSON<textarea value={council.policy} onChange={e=>setCouncil({...council,policy:e.target.value})}/></label><button className="primary" disabled={busy}>Create council</button></form>
 <form onSubmit={propose}><Head n="02" kicker="IMMUTABLE DIFF" title="Propose change"/><Grid><Field label="Council ID" value={proposal.councilId} set={v=>setProposal({...proposal,councilId:v})}/><Field label="Voting hours" type="number" value={proposal.hours} set={v=>setProposal({...proposal,hours:v})}/></Grid><Field label="Old full commit SHA" value={proposal.oldCommit} set={v=>setProposal({...proposal,oldCommit:v})}/><Field label="Old LICENSE SHA-256" value={proposal.oldDigest} set={v=>setProposal({...proposal,oldDigest:v})}/><Field label="New full commit SHA" value={proposal.newCommit} set={v=>setProposal({...proposal,newCommit:v})}/><Field label="New LICENSE SHA-256" value={proposal.newDigest} set={v=>setProposal({...proposal,newDigest:v})}/><button className="primary" disabled={busy}>Create case</button></form></section>
 <section id="cases" className="cases"><div className="section-head"><Head n="03" kicker="FACTS → VOTES" title="Council cases"/><label>Case<select value={selected} onChange={e=>setSelected(e.target.value)}>{cases.length?cases.map(x=><option key={x.case_id}>{x.case_id}</option>):<option>0</option>}</select></label></div>{active?<article className="case"><div className="case-top"><div><span className={`pill ${active.decision}`}>{active.decision}</span><h3>{active.assessment}</h3><p>{short(active.old_commit)} → {short(active.new_commit)}</p></div><div className="tally"><b>{active.accept_votes}</b><span>accept</span><b>{active.reject_votes}</b><span>reject</span><b>{active.total_votes}</b><span>total</span></div></div><div className="case-evidence"><span>Verified license revisions</span>{activeCouncil&&<><a href={licenseAt(active.old_commit)} target="_blank" rel="noopener noreferrer">Baseline commit ↗</a><a href={licenseAt(active.new_commit)} target="_blank" rel="noopener noreferrer">Candidate commit ↗</a></>}{diagnostics?.provenance_ok&&<strong>Provenance verified</strong>}</div><p className="decision-note">The assessment describes the license change. The council decision is determined separately by member votes and quorum.</p><div className="case-actions"><button disabled={busy||active.assessed} onClick={()=>write('assess_change',[BigInt(active.case_id)])}><GitCompare/> Assess evidence</button><select value={choice} onChange={e=>setChoice(e.target.value)}><option>ACCEPT</option><option>REJECT</option><option>ABSTAIN</option></select><button disabled={busy||!active.assessed||active.decision!=='PENDING'} onClick={()=>write('vote',[BigInt(active.case_id),choice])}><Vote/> Cast vote</button><button disabled={busy||active.decision!=='PENDING'} onClick={()=>write('finalize_case',[BigInt(active.case_id)])}>Finalize</button></div></article>:<div className="empty">No case exists yet. Create a council and propose an immutable license comparison.</div>}</section>
 <section className="boundary"><h2>Trust boundary</h2><p>GitHub proves which bytes exist at the declared repository commit. Validators determine a bounded semantic relationship between those bytes. Neither one decides whether your community accepts the change—the council does.</p></section></main><footer>RepoLicenseCouncil · Synthetic demonstration project · Not legal advice.</footer></div>}
function Field({label,value,set,type='text'}){return <label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}function Grid({children}){return <div className="grid">{children}</div>}function Head({n,kicker,title}){return <div className="head"><span>{n}</span><div><small>{kicker}</small><h2>{title}</h2></div></div>}function Stat({label,value}){return <div className="stat"><span>{label}</span><b>{value}</b></div>}
